import { CLASSIC_TRANSITION_EVENTS } from './classic-transitions.js';
import { CLASSIC_WIRE_KEYS, RUN_WIRE_KEYS } from './classic-state.js';
import { FIELD_ENUMS, SETTABLE_FIELDS } from './classic-state-options.js';

const OUTPUT_HELP =
  '\nOptions: --json (machine-readable output), --help\n' +
  'JSON: one object with command and exitCode; data, stdout, stderr, summary and next are optional.\n' +
  'Use exitCode for success; do not parse human-readable stdout. Help text is in stdout in JSON mode.\n';

/** Public invocation syntax, shared by the CLI and self-contained bundles. */
export function classicCommandHelp(command: string, args: readonly string[]): string | undefined {
  const boundary = args.indexOf('--');
  const ownArgs = boundary < 0 ? args : args.slice(0, boundary);
  if (!ownArgs.includes('--help') && !ownArgs.includes('-h')) return undefined;
  // OpenSpec owns its forwarded arguments, including help.
  const usage: Record<string, string[]> = {
    check: [
      'comet check run <change> <build|verify> [--local] [--incremental] [--cwd <path>] [--timeout-ms <ms>] -- <program> [args...]',
      'comet check rerun <change> <build|verify>',
      '--local opts deterministic local checks into same-input reuse; other checks are single-use.',
      '--incremental records phase-local evidence: guard previews accept it, --apply requires a full rerun.',
      'Arguments after -- belong to the child. Windows batch arguments containing shell syntax are rejected.',
      '',
      'Executes a program for an active change and stores its log and input-bound evidence.',
      '--local is not a location switch: all checks execute locally. It asserts deterministic inputs.',
      'Use --local only when no network, external state or untracked ignored inputs affect the result.',
      'Default evidence is single-use; reusable evidence requires matching inputs, environment and log.',
      '--cwd: relative to the project root; default is the invocation directory; must stay inside the project.',
      'Guard reuses evidence only when its cwd matches the guard invocation directory, or the command is declared with that cwd in a v2 check policy.',
      '--timeout-ms: default 300000; integer range 1..3600000.',
      'Place Comet options, including --json, before --. Child --help and --json after -- are forwarded.',
      '',
      'Result: data.scope, data.argv, data.cwd, data.exitCode, data.logRef, data.reusable; data.reused is optional.',
      'Exit: 0 = success with stable inputs; child failures propagate; timeout = 124; invalid invocation/runtime error = 70.',
      'A child exit of 0 with changed inputs returns exitCode 1. Use top-level exitCode, not data.exitCode.',
      'On failure inspect data.logRef or stderr, fix the cause, then rerun. Recovery revalidates local evidence.',
      'rerun repeats the latest Runtime-recorded argv, cwd, timeout and reuse tier without reconstructing shell syntax.',
      'Optional .comet/check-policy.json binds declared deterministic commands by exact argv and cwd.',
      'A v1 single-command object stays valid; v2 {"commands":[...]} scopes each command separately.',
      "Editing one v2 command entry invalidates only that command's evidence; unmatched commands stay conservative.",
      'Default inputs are the working-tree files. Declare git: "all" for builds that read HEAD or the index,',
      'env variable names whose values affect the result, and taskCheckboxes: "include" when completion marks matter.',
      'files accept literal paths and * ? ** globs; a new file matching a glob is checked without re-declaring.',
      'Declare every real input; do not infer dependencies from the current diff.',
      'Policy example: {"version":2,"commands":[{"argv":["node","scripts/build.mjs"],"cwd":".","files":["src/**","package.json"],"git":"all"},{"argv":["node","--test"],"cwd":".","files":["src/**","test/**"],"taskCheckboxes":"ignore"}]}',
      'Build evidence does not substitute for verify evidence. A successful compat check does not advance the phase.',
      'SDK checks submit their evidence to the pending Run and may advance its phase; data.phase, data.run and data.nextAction report the committed result.',
      '',
      'Examples: (replace demo with your active change; these commands execute code)',
      '  comet check run demo verify --json -- node --test',
      '  comet check run demo build --local --cwd . -- npm run build',
      '  comet check rerun demo build',
    ],
    state: [
      'comet state <command> [args]',
      'init <change-name> <full|hotfix|tweak> [--isolation <current|branch|worktree>] [--runtime <compat|sdk>]',
      'state init defaults to sdk in Git roots and compat in non-Git roots for document-only archive; pass --runtime compat to choose compat explicitly.',
      'restore <change-name> --confirmed (recover a copied SDK Run; older states without a checkpoint restart at Open)',
      'get <change-name> <field> [<field> ...]',
      'set <change-name> <field> <value> [<field> <value> ...]',
      'propose-design <change-name> --proposal <text> (SDK full workflow)',
      'revise-design <change-name> --expected-revision <number> (SDK full workflow)',
      'decide-design <change-name> --proposal-hash <sha256> --choice <approved|rejected> (SDK)',
      'complete-design <change-name> --design-doc <repo-relative-ref> [--approval-hash <sha256>]',
      'propose-build <change-name> --file <json> (SDK full workflow)',
      'decide-build <change-name> --proposal-hash <sha256> --choice <approved|rejected>',
      'submit-plan <change-name> --plan <repo-relative-ref> [--pause]',
      'revise-plan <change-name> --expected-revision <number> (SDK full workflow)',
      'continue-plan <change-name> --proposal-hash <sha256>',
      'complete-build <change-name>',
      'propose-escalation <change-name> --reason <text> (SDK hotfix/tweak)',
      'decide-escalation <change-name> --proposal-hash <sha256> --choice <continue|upgrade> (SDK)',
      'propose-archive <change-name> --summary <text> [--remote <name>] [--pr-base <branch>] (SDK)',
      'decide-archive <change-name> --proposal-hash <sha256> --choice <local|push|pr|reverify|later> (SDK)',
      'complete-delivery <change-name> --commit <sha> [--pr-url <url>] (SDK)',
      'transition <change-name> <event>',
      'transition <change-name> verify-fail --reason <text> (SDK)',
      'check <change-name> <phase> [--recover] [--details]',
      'scale <change-name>',
      'artifacts <change-name>',
      'record-check <change-name> <build|verify> --command <text> --exit-code <int> [--cwd <path>]',
      'task-checkoff <file> <task-text>',
      'tasks <change-name> [--assign-ids]',
      'task-complete <change-name> <task-id> --expect <revision>',
      'sync-plan <change-name>',
      'checkpoint <change-name> [--file <json>]',
      'delivery <change-name> [--file <json> | --verify]',
      'select <change-name> [--details] | rebind <change-name> | next <change-name> [--details]',
      'current | clear-selection',
      '',
      'Start with current or next <change-name> to inspect workflow guidance.',
      'Advanced writes: init, set, transition, task-checkoff, select, rebind, clear-selection.',
      'Use comet state <command> --help for details. --recover is for cold recovery, not normal progression.',
      'A copied SDK change with a Run checkpoint in .comet.yaml resumes at its saved phase. If the checkpoint is absent, state restore requires confirmation and restarts at Open with fresh approvals and checks.',
      'For SDK Design, propose-design records the exact proposal before asking the user; decide-design accepts only its current hash and may return a rejected proposal to Design. complete-design requires the approved hash and records the Design Doc in the same Run.',
      'For SDK Build, propose-build reads build_mode, tdd_mode, review_mode and subagent_dispatch from a project-relative JSON file; optional direct_override is required for full direct execution. Workspace isolation remains the Open decision.',
      'decide-build resolves only the current proposal. Rejecting it returns to configuration; approving it stores the choices and advances to planning.',
      'submit-plan validates the plan and its tasks.md authority before recording both the Action and evidence in the SDK Run. --pause requires an explicit continue-plan decision before execution.',
      'continue-plan accepts only the current plan-ready proposal and rejects changes to the approved plan or tasks.',
      'After source or plan changes, use the revision-bound revise-design or revise-plan command returned by recovery guidance; old approvals and accepted evidence cannot authorize changed content.',
      'complete-build accepts finished full-workflow tasks only, then advances the SDK Run to its Runtime check Action. A passing check receipt is required before Verify.',
      'For SDK hotfix/tweak, propose-escalation records why full Design is needed; decide-escalation applies only the current user choice. Upgrading continues the same Run and workspace through full Design.',
      'For SDK Archive, propose-archive binds the current branch and verified change to a user decision; decide-archive accepts only its current proposal hash. A local, push, or PR choice is required before the Archive Guard can perform filesystem archiving.',
      'After an SDK Archive, commit only the approved change files; complete-delivery validates that commit and any approved remote or PR before closing the Run. It does not create the commit, push, or PR.',
      'For compat Design, complete-design registers the reference, refreshes handoff, and applies the guard; interrupted retries retain completed work.',
      'Use data.artifactRefs for state references and task-authority markers; absolute paths are for file operations.',
    ],
    guard: [
      'comet guard <change-name> <open|design|build|verify|archive> [--apply]',
      'SDK-owned full Design: comet guard <change-name> design --design-doc <repo-relative-ref> [--apply --approval-hash <sha256>]',
      'SDK Design preview reads the current proposal, handoff and document without advancing the Run; apply requires the matching user approval hash.',
      'SDK-owned Build: comet guard <change-name> build [--apply [-- <program> [args...]]]',
      'SDK Build preview is read-only; apply completes the Build Action and runs a literal or unambiguous detected build check before Verify.',
      'SDK-owned Verify: comet guard <change-name> verify --report <repo-relative-ref> [--apply -- <program> [args...]]',
      'SDK Verify preview checks the report and pending Run without advancing it; apply submits report evidence and runs a literal verification check before Archive. An interrupted successful check can resume with --apply and no program.',
      'SDK-owned Archive: comet guard <change-name> archive [--apply]',
      'SDK Archive preview checks the approved delivery and current Verify evidence; apply runs preflight and OpenSpec Archive once. Commit, push, and PR delivery remain a separate pending SDK Action.',
      'Compat Guard validates phase requirements; --apply advances the phase after all checks pass.',
      'Compat Build preview is not read-only: it may execute a detected build and write evidence/logs.',
      'Preview does not consume single-use evidence. Successful phase advancement consumes it atomically.',
      'Failed or repeated previews preserve evidence; changed inputs still require a new check.',
      'Do not poll guard for status. Use comet state next <change-name> for guidance.',
      'On failure follow the reported next action; do not blindly retry side-effecting checks.',
      '',
      'Examples:',
      '  comet guard demo build --apply --json',
      '  comet state next demo --json',
    ],
    handoff: [
      'comet handoff <change-name> design --write [--full]',
      'comet handoff <change-name> --hash-only',
    ],
    archive: [
      'comet archive <change-name> [--dry-run|--recover]',
      '--recover reconciles one moved SDK Archive after the original executor has stopped; it never runs OpenSpec Archive again.',
    ],
    validate: ['comet classic validate <change-name>'],
    workspace: [
      'comet classic workspace prepare <change-name> --isolation <current|branch|worktree> [--change-branch <branch>] [--target-branch <branch>] [--worktree-path <path>]',
      'comet classic workspace resolve <change-name>',
    ],
  };
  const stateDetails: Record<string, string[]> = {
    current: [
      'comet state current',
      'Reports the selected Classic change. Does not advance the phase.',
    ],
    next: [
      'comet state next <change-name> [--details]',
      'Reports the next workflow action. Does not execute build or verification checks.',
      'SDK JSON includes recovery paths, configuration, compact task state and current Run handles. --details expands tasks, checkpoint content and full Run history.',
    ],
    select: [
      'comet state select <change-name> [--details]',
      'Writes the current change selection used by workflow routing.',
      'SDK JSON includes recovery paths, configuration, compact task state and current Run handles. --details expands tasks, checkpoint content and full Run history.',
    ],
    rebind: [
      'comet state rebind <change-name>',
      'Updates the change branch binding to the current Git branch after validation.',
    ],
    'clear-selection': [
      'comet state clear-selection',
      'Clears the current change selection; does not delete change artifacts.',
    ],
    init: [
      'comet state init <change-name> <full|hotfix|tweak> [--isolation <current|branch|worktree>]',
      'Creates Classic workflow state. Follow the Open workflow for required user decisions.',
    ],
    scale: [
      'comet state scale <change-name>',
      'Reports a verification recommendation without changing verify_mode.',
      'JSON: data.recommendation, data.selected and data.metrics. Scale is not a risk assessment.',
      'Preserve an existing selection; record a new decision explicitly with state set when needed.',
    ],
    artifacts: [
      'comet state artifacts <change-name>',
      'Inspects the OpenSpec apply dependency closure, including dependencies of already-complete artifacts.',
      'JSON: data.source, required, skipped, designRequired, files and problems. This does not execute implementation or verification.',
      'Optional design is omitted only when the active schema excludes it from the required closure.',
      'Skipped specs require explicit skip_specs: true, upstream support and no conflicting spec files.',
      'Compat changes without .openspec.yaml retain the existing Classic artifact requirements.',
    ],
    'task-checkoff': [
      'comet state task-checkoff <file> <task-text>',
      'Checks that exactly one matching task is already checked. Does not write the task file or execute the task.',
    ],
    tasks: [
      'comet state tasks <change-name> [--assign-ids]',
      'Reads tasks.md as the task completion authority. Fenced examples are excluded.',
      '--assign-ids persists IDs for legacy/new tasks in Open, Design or Build; existing IDs remain unchanged.',
      'Assign IDs before generating the design handoff and plan. ID assignment changes task requirements.',
      'JSON: data.authority, data.revision, data.needsIds, data.tasks and data.progress.',
      'Each task has id, text, completed and line. Never use line/order as task identity.',
      'Example: comet state tasks demo --assign-ids --json',
    ],
    'task-complete': [
      'comet state task-complete <change-name> <task-id> --expect <revision>',
      'Records accepted task completion during Build; does not execute or independently verify work.',
      'Use the revision returned by state tasks. Changed requirements reject the write; refresh and reassess the task.',
      'Writes tasks.md under the state lock and synchronizes explicitly ID-mapped legacy plan checkboxes. Retries repair interrupted projection writes.',
      'Reconcile code, checks and review evidence before recording completion; unchecked does not mean unimplemented.',
      'Unmapped legacy items are preserved and reported as mapping-required; never match tasks by position or wording.',
    ],
    'sync-plan': [
      'comet state sync-plan <change-name>',
      'Synchronizes legacy plan checkboxes from tasks.md by explicit comet-task IDs; does not execute or accept work.',
      'Rejects missing or unknown plan IDs. Reconcile extra requirements into tasks.md before mapping.',
      'New plans should reference task IDs without a second completion checklist.',
    ],
    checkpoint: [
      'comet state checkpoint <change-name> [--file <json>]',
      'Reads a structured coordination checkpoint, or records an explicitly bounded work package during Build.',
      'Input: taskIds, revision, stage, sessionId, evidence, unresolved, reviewRounds.',
      'Include schemaVersion: 1. JSON state is .comet/coordination.json, separate from the Engine checkpoint.',
      'Stages: implementing|task-review|checkoff|done|blocked. Evidence is a coordination record, not automatic acceptance.',
      'Runtime checks task IDs and revision and renders subagent-progress.md. Do not maintain its projection manually.',
    ],
    delivery: [
      'comet state delivery <change-name> [--file <json> | --verify]',
      'Reads delivery authorization and observed progress, or records the user-authorized local|push|pr action.',
      'Input: action, targetBranch, optional remote, commit and prUrl. Recording never performs remote writes.',
      'First authorization requires Archive with passing verification before archival. Missing legacy authorization is never inferred.',
      'Resume only authorized unfinished steps; supplied commit or PR text alone does not prove delivery.',
      '--verify performs bounded read-only remote/PR verification; normal entry never contacts the network.',
    ],
    get: [
      'comet state get <change-name> <field> [<field> ...]',
      'Reads the requested fields from one state snapshot. JSON: data.change and data.fields (string values).',
      'One field preserves the bare stdout value; multiple fields print field=value lines in request order.',
      `Fields: ${[...CLASSIC_WIRE_KEYS, ...RUN_WIRE_KEYS].join(', ')}`,
      'Example: comet state get demo phase --json',
      'Example: comet state get demo phase workflow build_mode tdd_mode review_mode --json',
    ],
    set: [
      'comet state set <change-name> <field> <value> [<field> <value> ...]',
      'Advanced: validates all fields, then commits one atomic state update and reconciles Runtime state.',
      'Invalid values or duplicate fields reject the whole update. Do not bypass workflow confirmations.',
      'JSON: data.change and data.updated contain the committed field values.',
      'Writable fields (enum values shown where applicable):',
      ...[...SETTABLE_FIELDS].map(
        (field) =>
          `  ${field}${FIELD_ENUMS[field] ? `: ${FIELD_ENUMS[field].join('|')}` : field === 'language' ? ': en|zh-CN' : ''}`,
      ),
      'Other Runtime-owned fields cannot be set manually. Artifact paths must stay within the project.',
      'Example: comet state set demo verify_mode full',
      'Example: comet state set demo build_mode executing-plans tdd_mode direct review_mode standard --json',
    ],
    check: [
      'comet state check <change-name> <open|design|build|verify|archive> [--recover] [--details]',
      'Checks phase entry requirements; this is not a build/test execution command.',
      '--recover is for cold recovery after context loss, not normal phase progression.',
      'Recovery revalidates reusable local evidence and invalidates stale, damaged or single-use evidence.',
      'It preserves completed work; resume from the checkpoint and rerun required checks before progressing.',
      'JSON entry data includes layout, configuration, configurationReadiness, nextAction, compact taskState, planMapping and checks.',
      '--recover additionally revalidates evidence and includes checkpoint references; --details expands tasks, checkpoint content and full SDK Run history.',
      'Reconcile existing implementation and acceptance before dispatching work; unchecked tasks are not proof of missing implementation.',
      'Read fresh state after changing configuration or advancing phases; do not reuse an earlier entry snapshot.',
      'SDK entry, proposal, decision and completion results include nextAction from that Run revision, with Action, evidence or decision handles. User approval and fresh validation are still required for subsequent writes.',
      '',
      'Examples:',
      '  comet state check demo build --json',
      '  comet state check demo build --recover --json',
    ],
    'revise-design': [
      'comet state revise-design <change-name> --expected-revision <number>',
      'Reopens SDK full Design for a revised proposal from Design or stopped Build work, retaining prior decisions and implementation history.',
      'Use the current Run revision from state next or state check --recover. A stale revision is rejected.',
      'Then propose-design with the revised design and any agreed Spec Patch, obtain a new explicit user decision, and decide-design with the new proposal hash.',
      'Revision does not approve the new design. Old approval hashes do not authorize changed requirements.',
    ],
    'revise-plan': [
      'comet state revise-plan <change-name> --expected-revision <number>',
      'Reopens SDK full planning after accepted plan content changes, retaining completed implementation and prior evidence history.',
      'Use the current Run revision from state next or state check --recover. A stale revision is rejected.',
      'Then submit-plan with the revised plan and current task mapping. Use --pause when the user requested a planning pause; continue only with the new plan-ready proposal hash.',
      'Revision does not accept the new plan or bypass task authority, design approval, or Runtime checks.',
      'Changed requirements or task scope require revise-design and a fresh Design approval before resubmitting the plan.',
    ],
    restore: [
      'comet state restore <change-name> --confirmed',
      'Only for a copied SDK change whose .comet.yaml survived but local Run history did not.',
      'Confirm the original execution process stopped before using this command. A portable checkpoint restores the saved phase and decisions; an older state without one restarts at Open and requires fresh evidence and approvals.',
      'Unknown external actions are not replayed. A branch binding mismatch or archived change is rejected.',
    ],
    'record-check': [
      'comet state record-check <change> <build|verify> --command <text> --exit-code <int> [--cwd <path>]',
      'Advanced: writes a manual attestation; does not execute the command.',
      'A manual attestation cannot satisfy Runtime build/verify evidence requirements, even with exit code 0.',
      'Use comet check run to execute a check and obtain evidence that guard can validate.',
      '--cwd: relative to project root, defaults to .; must stay inside the project.',
      '',
      'Examples:',
      '  comet state record-check demo verify --command "external test run" --exit-code 1',
      '  comet check run demo verify --json -- node --test',
    ],
    transition: [
      'comet state transition <change-name> <event>',
      'SDK: comet state transition <change-name> verify-fail --reason <text>',
      `Events: ${CLASSIC_TRANSITION_EVENTS.join(', ')}`,
      'Advanced: applies a state-machine event and writes workflow state. Required confirmations still apply.',
      'This is not a substitute for the workflow Skill or phase guard. Use state next for the next action.',
    ],
  };
  const subcommand = ownArgs.find((arg) => !arg.startsWith('-'));
  const lines = (command === 'state' && subcommand && stateDetails[subcommand]) || usage[command];
  return lines
    ? `Usage: ${lines.join('\n  ')}\n${OUTPUT_HELP}Command placeholders must be replaced with actual values.\n`
    : undefined;
}
